ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.slasher_risk]
path = "out/SlasherTrap.sol/SlasherTrap.json"
response_contract = "0x365a97a1dda46bff1e3a916a6bb69043181f4d1c"
response_function = "respondWithSlashingAlert(address,uint256,uint256,string)"
cooldown_period_blocks = 30
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 20
private_trap = true
whitelist = ["0x83cd7e5604ff5823734ddfbd82820c0965498284"]
address = "0x73DE6eB262483D97b8675D1f6d00efC7183C32C1"
